name: wheels-macos

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      # Python "driver" per lanciare cibuildwheel (non influisce sui cp target)
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install cibuildwheel
        run: python -m pip install -U cibuildwheel

      - name: Build wheels (macOS arm64, cp311/cp312/cp313)
        env:
          FITWVB_VENDORIZE: "1"                 # usa rpath @loader_path
          CIBW_REPAIR_WHEEL_COMMAND: ""         # disabilita delocate (non vendorizzi Qt/PySide)
        run: python -m cibuildwheel --output-dir dist

      - name: Upload wheels artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheels-macos
          path: dist/*.whl

